pipelines:
  MyFirst:
    group: test
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/hiyer28/sampleapp.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - checkout:
          clean_workspace: true
          keep_artifacts: true
          fetch_materials: true
          jobs:
            GetRepo:
              tasks:
                - script: |
                    echo Getting repo..             
    - Deployment:
          clean_workspace: true
          keep_artifacts: true
          fetch_materials: false
          jobs:
            Deploy:
              tasks:
                - script: |
                    echo Getting repo..


