format_version: 3
pipelines:
  Test:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/gocd-contrib/getting-started-repo.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - defaultStage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          defaultJob:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - test
                command: echo
                run_if: passed
